name: deploy

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "20.13"

      - name: Install pnpm
        run: corepack enable

      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.ymal') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      # 运行构建脚本
      - name: Build VuePress site
        run: export NODE_OPTIONS=--max_old_space_size=10240 && pnpm run docs:build

      - name: Set VuePress CNAME
        run: cd docs/.vuepress/dist && echo 'blog.zkkysqs.top' > CNAME && cd -

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        # 环境变量
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
