name: deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        use: actions/setup-node@v4
        with:
          node-version: "16.8"
          cache: 'npm'

      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      # 运行构建脚本
      - name: Build VuePress site
        run: export NODE_OPTIONS=--max_old_space_size=10240 && yarn docs:build

      - name: Set VuePress CNAME
        run: cd docs/.vuepress/dist && echo 'blog.zkkysqs.top' > CNAME && cd -
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}